server:
  port: 8080

spring:
  application:
    name: pedidos360-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.dxcboyfuwcpejgpnqton}
    password: ${SPRING_DATASOURCE_PASSWORD:Pedidos360@}

  jpa:
    database-platform: ${SPRING_JPA_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

app:
  security:
    issuer: ${JWT_ISSUER:https://login.microsoftonline.com/16c2a7cf-f000-475f-a847-f95ee0b36404/v2.0}
    audience: ${JWT_AUDIENCE:aef48164-1df8-49e6-b9f2-c1d8953ea200}
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:5173,http://localhost:3000}